# SOK-1006 Mikro
## Seminar 2
### Oppgave 1

In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import sympy as sp

In [29]:
# last inn data

df=pd.read_csv("https://uit-sok-1006-v22.github.io/seminarer/suits_watermelons.csv",delimiter=";")

In [30]:
df

,Year,log q,log h,log p,log p_c,log p_v,log w,log n,log(y/n),log p_f
0,1930,4.448623,4.379545,4.761777,2.247338,0.845054,3.366401,4.812434,6.403531,2.535163
1,1931,4.356519,4.333493,4.614410,1.733858,2.726278,3.136141,4.819342,6.244651,2.546676
2,1932,4.204548,4.054879,4.368032,1.874316,2.588122,2.832198,4.826250,5.966037,2.599635
3,1933,4.031853,4.008827,4.531517,2.318718,2.286482,2.772330,4.833157,5.896959,2.645687
4,1934,4.096325,4.094023,4.644344,2.514439,1.475967,2.917394,4.840065,6.018996,2.624964
5,1935,4.195337,4.156193,4.563753,2.406217,1.892737,2.970354,4.844670,6.129521,2.710160
6,1936,4.135470,4.128562,4.851578,2.514439,1.897342,2.995683,4.853881,6.246954,2.703252
7,1937,4.262113,4.225271,4.662765,2.129905,2.079248,3.113115,4.858486,6.311427,2.705555
8,1938,4.259810,4.202245,4.690396,2.150628,3.044037,3.090089,4.865394,6.226230,2.753910
9,1939,4.144680,4.137772,4.777895,2.208193,1.701621,3.113115,4.874604,6.288401,2.691739
10,1940,4.345006,4.282836,4.690396,2.291087,2.535163,3.136141,4.883815,6.355176,2.753910
11,1941,4.165403,4.165403,4.897630,2.834501,3.161470,3.295021,4.893025,6.546292,2.758515
12,1942,4.034155,4.034155,5.480188,2.947328,3.893697,3.525281,4.904538,6.769644,2.744699
13,1943,3.882184,3.882184,6.097285,2.988775,3.642713,3.794685,4.918354,6.884774,2.643385
14,1944,4.259810,4.259810,5.908472,3.032524,2.390099,3.988103,4.929867,6.965365,2.634174
15,1945,4.289744,4.289744,6.016694,3.115418,1.853593,4.126259,4.941380,6.979181,2.696345
16,1946,4.393361,4.388756,5.949918,3.486136,3.430874,4.262113,4.950590,7.025233,2.694042
17,1947,4.395663,4.326585,5.765710,3.463110,3.460808,4.331191,4.971313,7.066679,2.869040
18,1948,4.301257,4.301257,5.963734,3.414756,3.981195,4.381848,4.987432,7.154178,3.087787
19,1949,4.361124,4.358822,5.742684,3.352586,2.733186,4.356519,5.005852,7.140363,3.168378
20,1950,4.411782,4.326585,5.777223,3.691068,1.883527,4.370335,5.021971,7.214046,3.219035
21,1951,4.423295,4.414084,5.910774,3.635805,NaN,NaN,5.040391,7.290032,3.267389

In [ ]:
#Variable	Description
#Year	Year (1930-1951)
#log q (Q)	Total number of watermelons available for harvest (millions)
#log h (X)	Watermelons harvested (millions)
#log p (P)	Average farm price of watermelons ($ per 1000)
#log p_c (C)	Average annual net farm receipts per pound of cotton (dollars)
#log p_v (T)	Average farm price of vegetables (index)
#log w (W)	Farm wage rates in the South Atlantic States (index)
#log n (N)	US population 
#log(y/n) (Y/N)	Per capita disposable income ($)
#log p_f (F)	Railway freight costs for watermelons (index)